Change the comment of BatchGetEffectiveIamPolicies to be more accurate.
googleapis/python-asset pull request #499
Opened 2022-09-20 23:33 UTC by jeffreyaiatgoogle

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-asset/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-09-27 03:12 UTC, dandhlee requested changes

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_delete_saved_query_test.py
> +# Copyright 2018 Google LLC.
```suggestion
# Copyright 2022 Google LLC.
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_get_saved_query.py
> +# Copyright 2018 Google LLC.
```suggestion
# Copyright 2022 Google LLC.
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_get_saved_query.py
> +    print("gotten_saved_query: {}".format(response))
```suggestion
    print(f"gotten_saved_query: {response}")
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_get_saved_query_test.py
> +# Copyright 2018 Google LLC.
```suggestion
# Copyright 2022 Google LLC.
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_list_saved_queries.py
> +# Copyright 2018 Google LLC.
```suggestion
# Copyright 2022 Google LLC.
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_list_saved_queries.py
> +    print("saved_queries: {}".format(response.saved_queries))
```suggestion
    print(f"saved_queries: {response.saved_queries}")
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_list_saved_queries_test.py
> +# Copyright 2018 Google LLC.
```suggestion
# Copyright 2022 Google LLC.
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_list_saved_queries_test.py
> +    parent_resource = "projects/{}".format(PROJECT)
```suggestion
    parent_resource = f"projects/{PROJECT}"
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_create_saved_query_test.py
> +    assert "saved_query" in out
All the tests in general only seem to be checking that RPC calls are made. The tests should check that (1) RPC calls are made, but also (2) check the contents of the response (delete doesn't return the response in the API so listing for empty queries or something would also work), to ensure that the tests are accurate.

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_update_saved_query.py
> +# Copyright 2018 Google LLC.
```suggestion
# Copyright 2022 Google LLC.
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_update_saved_query.py
> +    print("updated_saved_query: {}".format(response))
```suggestion
    print(f"updated_saved_query: {response}")
```

2022-09-27 03:12 UTC, dandhlee commented on samples/snippets/quickstart_update_saved_query_test.py
> +# Copyright 2018 Google LLC.
```suggestion
# Copyright 2022 Google LLC.
```

2022-09-27 03:13 UTC, dandhlee commented on samples/snippets/quickstart_get_saved_query.py
> +    # [START asset_quickstart_get_saved_query]
Snippet bot complaints:

```suggestion
    # [END asset_quickstart_get_saved_query]
```

2022-09-27 23:30 UTC, jeffreyaiatgoogle commented on samples/snippets/quickstart_create_saved_query.py
> +    # TODO: add more details into your saved query here.
I will add a link to the saved query content reference page to help user to compose their own saved query.

2022-09-27 23:31 UTC, jeffreyaiatgoogle commented on samples/snippets/quickstart_create_saved_query.py
> +    scope = "organizations/474566717491"  # Change to your org, folder. or project
I will remove the scope here and add a TODO comment later to let users to compose their saved query based on their need.

2022-09-29 06:01 UTC, dandhlee commented on samples/snippets/quickstart_create_saved_query.py
> +    # TODO: add more details into your saved query here.
TODO's by itself can be left abandoned, could you file an issue as well? 😅

2022-11-18 21:08 UTC, dandhlee commented on samples/snippets/quickstart_create_saved_query.py
> +    saved_query.content.iam_policy_analysis_query.access_selector.permissions.append("iam.serviceAccounts.actAs")
nit: line length
```suggestion
query_access_selector = saved_query.content.iam_policy_analysis_query.access_selector
query_access_selector.permissions.append("iam.serviceAccounts.actAs")
```

2022-11-18 21:23 UTC, dandhlee commented on samples/snippets/quickstart_create_saved_query_test.py
> +    assert "saved_query" in out
Closing the loop: not in scope for this sample. Current checks are fine.

2022-11-18 21:24 UTC, dandhlee approved these changes
LGTM

2022-11-18 21:25 UTC, dandhlee commented
Editing to `chore(samples)` to not trigger a release.

2022-11-18 21:26 UTC, merged